/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "scheduler.h"

void enable_processor_faults(void);

void enable_processor_faults(void) {
  uint32_t *const pSHCSR = (uint32_t *)0xE000ED24;
  *pSHCSR |= (1 << 16);  // mem manage
  *pSHCSR |= (1 << 17);  // bus handler
  *pSHCSR |= (1 << 18);  // usage fault
}


int main(void) {
  enable_processor_faults();
  init_scheduler_stack(SZ_SCHEDULER_STACK);
  for (;;)
    ;
}

void MemManage_Handler(void) {
  printf("MemManage_Handler");
  while (1)
    ;
}

void UsageFault_Handler(void) {
  printf("UsageFault_Handler");
  while (1)
    ;
}

void BusFault_Handler(void) {
  printf("BusFault_Handler");
  while (1)
    ;
}

void HardFault_Handler(void) {
  printf("HardFault_Handler");
  while (1)
    ;
}